spring:
  application:
    name: Collab-Project

  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.wcmigjlaaoplbydadlzx
    password: "Coll@bproject2025"
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        transaction:
          coordinator_class: jdbc
    show-sql: true

  rabbitmq:
    host: amqps://cow.rmq2.cloudamqp.com
    port: 5672
    username: slzjfjxx
    password: UsrrZc_Z1dWw2zz03GwpSGrRPDtrlzhX
    virtual-host: slzjfjxx

    # Configure rabbit mq exchanges, queues and routing keys
    exchanges:
      user: user.exchange
      chat: chat.exchange
      notification: notification.exchange
    queues:
      user: user.queue
      recommendation: recommendation.queue
      connection: connection.queue
      event: event.queue
    routingKeys:
      user.signup.key: user.signup

jwt:
  secret: av7Mp5zVtb3S467pWQ6A1MXRr0tBrqydU6+MeMfEQSw=


logging:
  level:
    web: DEBUG

    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

brevo:
  api:
    key: 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

    url: https://api.brevo.com/v3/smtp/email

app:
  email:
    from:
      address: dogovicky05@gmail.com
      name: Nexus

  verification:
    expiry-minutes: 15


cloudinary:
  cloud-name: dz3bxfeev
  api-key: 478173146141297
  api-secret: L1Dk5P_VnKOWqpiVB8hrIbczezs