spring.application.name = Collab-Project

spring.datasource.url = jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username = postgres.wcmigjlaaoplbydadlzx
spring.datasource.password = Coll@bproject2025
spring.datasource.driverClassName = org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc



